<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<h2>Sign in using this form</h2>

<?php echo $this->tag->form("/index/login"); ?>

    <p>
        <label for="username">Username</label>
        <?php echo $this->tag->textField("username"); ?>
    </p>
    <p>
        <label for="email">Password</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>
    
    <p>
        <?php echo $this->tag->submitButton("Login"); ?><br>
    </p>
</form>
<p>
   
</p>
</body>
</html>